[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/googlef5bb50339648d3a9.html"
  to = "/googlef5bb50339648d3a9.html"
  status = 200

