`use client`

import React from 'react';
import { FileText, Mail, Shield, Eye, Clock, Globe } from 'lucide-react';

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-100 rounded-lg">
              <Shield className="w-6 h-6 text-blue-600" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Privacy Policy</h1>
              <p className="text-gray-600">Core To Stack</p>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="bg-white rounded-xl shadow-sm border">
          <div className="p-8">
            {/* Last Updated Banner */}
            <div className="flex items-center gap-2 mb-8 p-4 bg-blue-50 rounded-lg border border-blue-200">
              <Clock className="w-5 h-5 text-blue-600" />
              <span className="text-blue-800 font-medium">Last updated: July 14, 2025</span>
            </div>

            {/* Introduction */}
            <section className="mb-8">
              <p className="text-gray-700 leading-relaxed mb-4">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>
              <p className="text-gray-700 leading-relaxed">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
            </section>

            {/* Interpretation and Definitions */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <FileText className="w-6 h-6 text-blue-600" />
                Interpretation and Definitions
              </h2>
              
              <h3 className="text-xl font-semibold text-gray-800 mb-3">Interpretation</h3>
              <p className="text-gray-700 leading-relaxed mb-6">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>

              <h3 className="text-xl font-semibold text-gray-800 mb-4">Definitions</h3>
              <div className="space-y-3">
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-gray-700"><strong>Company</strong> refers to Core To Stack, Complexo Building, Model Colony Karachi.</p>
                </div>
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-gray-700"><strong>Service</strong> refers to the Website.</p>
                </div>
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-gray-700"><strong>Website</strong> refers to coretostack, accessible from <a href="https://coretostack.netlify.app/" className="text-blue-600 hover:text-blue-800 underline" target="_blank" rel="noopener noreferrer">https://coretostack.netlify.app/</a></p>
                </div>
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-gray-700"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
                </div>
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-gray-700"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</p>
                </div>
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-gray-700"><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history.</p>
                </div>
              </div>
            </section>

            {/* Data Collection */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <Eye className="w-6 h-6 text-blue-600" />
                Collecting and Using Your Personal Data
              </h2>
              
              <h3 className="text-xl font-semibold text-gray-800 mb-3">Personal Data We Collect</h3>
              <p className="text-gray-700 leading-relaxed mb-4">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include:
              </p>
              <div className="grid md:grid-cols-2 gap-4 mb-6">
                <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
                  <p className="text-blue-800 font-medium">• Email address</p>
                </div>
                <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
                  <p className="text-blue-800 font-medium">• First name and last name</p>
                </div>
              </div>

              <h3 className="text-xl font-semibold text-gray-800 mb-3">Usage Data</h3>
              <p className="text-gray-700 leading-relaxed mb-4">
                Usage Data is collected automatically when using the Service. This may include information such as:
              </p>
              <div className="bg-gray-50 p-4 rounded-lg mb-6">
                <p className="text-gray-700">Your Device's IP address, browser type, browser version, pages visited, time and date of visit, time spent on pages, unique device identifiers and other diagnostic data.</p>
              </div>

              <h3 className="text-xl font-semibold text-gray-800 mb-3">How We Use Your Data</h3>
              <div className="grid gap-3">
                <div className="p-4 bg-green-50 rounded-lg border border-green-200">
                  <p className="text-green-800"><strong>Service Provision:</strong> To provide and maintain our Service</p>
                </div>
                <div className="p-4 bg-green-50 rounded-lg border border-green-200">
                  <p className="text-green-800"><strong>Account Management:</strong> To manage Your registration and account</p>
                </div>
                <div className="p-4 bg-green-50 rounded-lg border border-green-200">
                  <p className="text-green-800"><strong>Communication:</strong> To contact You with updates and information</p>
                </div>
                <div className="p-4 bg-green-50 rounded-lg border border-green-200">
                  <p className="text-green-800"><strong>Improvement:</strong> To analyze and improve our Service</p>
                </div>
              </div>
            </section>

            {/* Data Sharing */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Data Sharing</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                We may share Your personal information in the following situations:
              </p>
              <div className="space-y-3">
                <div className="p-4 bg-yellow-50 rounded-lg border border-yellow-200">
                  <p className="text-yellow-800"><strong>With Service Providers:</strong> To monitor and analyze the use of our Service</p>
                </div>
                <div className="p-4 bg-yellow-50 rounded-lg border border-yellow-200">
                  <p className="text-yellow-800"><strong>Business Transfers:</strong> In connection with mergers, acquisitions, or asset sales</p>
                </div>
                <div className="p-4 bg-yellow-50 rounded-lg border border-yellow-200">
                  <p className="text-yellow-800"><strong>With Your Consent:</strong> For any other purpose with Your consent</p>
                </div>
              </div>
            </section>

            {/* Your Rights */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Your Rights</h2>
              <div className="bg-blue-50 p-6 rounded-lg border border-blue-200">
                <h3 className="text-lg font-semibold text-blue-900 mb-3">You have the right to:</h3>
                <div className="space-y-2 text-blue-800">
                  <p>• Access and update your personal information</p>
                  <p>• Delete your personal data</p>
                  <p>• Request correction of inaccurate data</p>
                  <p>• Withdraw consent for data processing</p>
                </div>
              </div>
            </section>

            {/* Security */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Security</h2>
              <div className="p-4 bg-red-50 rounded-lg border border-red-200">
                <p className="text-red-800">
                  The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
              </div>
            </section>

            {/* Children's Privacy */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Children's Privacy</h2>
              <p className="text-gray-700 leading-relaxed">
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
              </p>
            </section>

            {/* Changes to Policy */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Changes to this Privacy Policy</h2>
              <p className="text-gray-700 leading-relaxed">
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.
              </p>
            </section>

            {/* Contact Information */}
            <section className="p-6 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg border border-blue-200">
              <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <Mail className="w-6 h-6 text-blue-600" />
                Contact Us
              </h2>
              <p className="text-gray-700 mb-3">
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <a 
                href="mailto:coretostack@gmail.com" 
                className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-800 font-medium"
              >
                <Mail className="w-4 h-4" />
                coretostack@gmail.com
              </a>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      {/* <footer className="bg-gray-900 text-white">
        <div className="max-w-4xl mx-auto px-4 py-8">
          <div className="text-center">
            <div className="flex items-center justify-center gap-2 mb-4">
              <Globe className="w-5 h-5" />
              <span className="font-medium">Core To Stack</span>
            </div>
            <p className="text-gray-400 text-sm">
              &copy; {new Date().getFullYear()} Core To Stack. All rights reserved.
            </p>
          </div>
        </div>
      </footer> */}
    </div>
  );
}